# Generated by Django 5.0 on 2024-10-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_entrees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sorties', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img.jpeg', upload_to='category')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prix_de_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_type', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(blank=True, default=0)),
                ('alert_stock', models.PositiveIntegerField(blank=True, default=10)),
                ('date_avaries', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ReapprovisionnementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('reapprovisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReapprovisionnementItem', to='pos.reapprovisionnement')),
            ],
        ),
    ]
