# Generated by Django 5.0 on 2024-10-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('pos', '0003_reapprovisionnement_autheur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reapprovisionnement',
            name='fournisseur',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.fournisseur'),
        ),
    ]
