# Generated by Django 5.0 on 2024-10-12 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_remove_reapprovisionnementitem_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reapprovisionnement',
            name='status',
            field=models.CharField(choices=[('Non Validé', 'Non Validé'), ('Validé', 'Validé')], default='Non Validé', max_length=50),
        ),
        migrations.AlterField(
            model_name='reapprovisionnementitem',
            name='reapprovisionnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.reapprovisionnement'),
        ),
    ]
