# Generated by Django 5.0 on 2024-10-15 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_reapprovisionnement_montant_paye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='historique_prix',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='pos.product')),
            ],
        ),
    ]
