# Generated by Django 5.0 on 2024-10-18 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_remove_product_historique_prix_caisse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dernier_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaisseHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_cloture', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CaisseJournal',
        ),
        migrations.RenameField(
            model_name='caisse',
            old_name='solde',
            new_name='solde_actuel',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='date',
        ),
        migrations.AddField(
            model_name='caisse',
            name='date_fermeture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caisse',
            name='date_ouverture',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caisse',
            name='is_cloture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caisse',
            name='solde_initial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caissehistorique',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='pos.caisse'),
        ),
        migrations.AddField(
            model_name='caissehistorique',
            name='user_cloture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
