# Generated by Django 5.0 on 2024-10-18 15:09

import django.db.models.deletion
import pos.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remboursementclient'),
        ('pos', '0011_remove_product_stock_product_stock_actuel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Validé', 'Validé'), ('Retournée', 'Retournée'), ('Annulé', 'Annulé'), ('Mis en pause', 'Mis en pause')], default='En cours', max_length=20)),
                ('status_de_paiement', models.CharField(choices=[('soldée', 'soldée'), ('non soldée', 'non soldée')], default='non soldée', max_length=20)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status_de_payement', models.CharField(blank=True, max_length=50)),
                ('validated_at', models.DateTimeField(auto_now=True, null=True)),
                ('add_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
                ('delete', models.BooleanField(default=False)),
                ('client', models.ForeignKey(default=pos.models.Order.get_default_client, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client')),
                ('server', models.ForeignKey(limit_choices_to={'role': 'WAITER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_product_name', models.CharField(blank=True, max_length=255)),
                ('custom_product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
    ]
