# Generated by Django 5.0 on 2024-10-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementstock',
            name='produit',
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_de_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pos.product')),
            ],
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='lot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pos.lot'),
        ),
    ]
