# Generated by Django 5.0 on 2024-10-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_remove_mouvementstock_produit_mouvementstock_motif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pos.lot'),
        ),
    ]
