# Generated by Django 5.0 on 2024-10-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_alter_mouvementstock_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_avaries',
        ),
    ]
