# Generated by Django 5.0 on 2024-10-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_product_add_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventaire',
            name='produits_inventories',
        ),
        migrations.RemoveField(
            model_name='inventairedetail',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='lot',
        ),
        migrations.AddField(
            model_name='inventaire',
            name='produits',
            field=models.ManyToManyField(through='pos.InventaireDetail', to='pos.fichestock'),
        ),
        migrations.AddField(
            model_name='inventairedetail',
            name='fiche_stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pos.fichestock'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='fiche_stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pos.fichestock'),
        ),
        migrations.AlterField(
            model_name='inventairedetail',
            name='inventaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pos.inventaire'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_at',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
