# Generated by Django 5.0 on 2024-10-25 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_remove_inventaire_produits_inventories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventaire',
            name='produits',
        ),
        migrations.AddField(
            model_name='inventaire',
            name='produits',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='InventaireDetail', to='pos.fichestock'),
        ),
    ]
