# Generated by Django 5.0 on 2025-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0019_product_code_product_image_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventaire",
            name="produits",
        ),
        migrations.RemoveField(
            model_name="inventairedetail",
            name="fiche_stock",
        ),
        migrations.RemoveField(
            model_name="mouvementstock",
            name="fiche_stock",
        ),
        migrations.RemoveField(
            model_name="inventaire",
            name="user",
        ),
        migrations.RemoveField(
            model_name="inventairedetail",
            name="inventaire",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="mouvementstock",
            name="user",
        ),
        migrations.RemoveField(
            model_name="reapprovisionnement",
            name="autheur",
        ),
        migrations.RemoveField(
            model_name="reapprovisionnement",
            name="fournisseur",
        ),
        migrations.RemoveField(
            model_name="reapprovisionnementitem",
            name="reapprovisionnement",
        ),
        migrations.RemoveField(
            model_name="reapprovisionnementitem",
            name="produit",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="prix_achat",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="alert_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="prix_de_vente",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_actuel",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_initial",
        ),
        migrations.AddField(
            model_name="product",
            name="update_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="FicheStock",
        ),
        migrations.DeleteModel(
            name="Inventaire",
        ),
        migrations.DeleteModel(
            name="InventaireDetail",
        ),
        migrations.DeleteModel(
            name="Lot",
        ),
        migrations.DeleteModel(
            name="MouvementStock",
        ),
        migrations.DeleteModel(
            name="Reapprovisionnement",
        ),
        migrations.DeleteModel(
            name="ReapprovisionnementItem",
        ),
    ]
