# Generated by Django 5.0 on 2025-03-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0022_orderitem_custom_product_price_currency_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-add_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True, default="Grand", max_length=100, null=True
            ),
        ),
    ]
