# Generated by Django 5.0 on 2025-03-27 15:00

import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import measurement.measures.volume
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0024_ingredient_stockentry_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="pos.product",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="ingredient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="pos.ingredient",
            ),
        ),
        migrations.CreateModel(
            name="ProductIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_required",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.mass.Mass,
                        null=True,
                    ),
                ),
                (
                    "volume_required",
                    django_measurement.models.MeasurementField(
                        blank=True,
                        measurement=measurement.measures.volume.Volume,
                        null=True,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="pos.ingredient",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="pos.product",
                    ),
                ),
            ],
        ),
    ]
