# Generated by Django 5.0 on 2025-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0026_remove_ingredient_unit_ingredient_entry_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="volume",
        ),
        migrations.RemoveField(
            model_name="productingredient",
            name="volume_required",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="volume_used",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[("l", "Litre"), ("unite", "Unité")], default="l", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="productingredient",
            name="unit",
            field=models.CharField(
                choices=[("l", "Litre"), ("unite", "Unité")], default="l", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="unit",
            field=models.CharField(
                choices=[("l", "Litre"), ("unite", "Unité")], default="l", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productingredient",
            name="quantity_required",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity_used",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
