# Generated by Django 5.0 on 2025-03-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0028_stockmovement_amount_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status_de_paiement",
        ),
    ]
