# Generated by Django 5.0 on 2025-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0029_remove_order_status_remove_order_status_de_paiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("En cours", "En cours"),
                    ("Validé", "Validé"),
                    ("Retournée", "Retournée"),
                    ("Annulé", "Annulé"),
                    ("Mis en pause", "Mis en pause"),
                ],
                default="En cours",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status_de_paiement",
            field=models.CharField(
                choices=[("soldée", "soldée"), ("non soldée", "non soldée")],
                default="non soldée",
                max_length=20,
            ),
        ),
    ]
