# Generated by Django 5.0 on 2025-03-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0030_order_status_order_status_de_paiement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delete",
        ),
    ]
