# Generated by Django 5.0 on 2025-03-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0032_remove_product_price_remove_product_price_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="size",
        ),
    ]
