# Generated by Django 5.0 on 2025-03-31 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0033_remove_orderitem_product_remove_orderitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pos.productsize",
            ),
        ),
    ]
