# Generated by Django 5.0 on 2025-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0037_alter_depense_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="daily_sequence",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
