# Generated by Django 5.0 on 2024-10-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
