# Generated by Django 5.0 on 2024-10-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0002_user_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='prenoms',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='default value', max_length=50),
        ),
    ]
