# Generated by Django 5.0 on 2025-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnels", "0003_user_address_user_nom_user_prenoms_user_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="nom",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="prenoms",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(max_length=50),
        ),
    ]
