# Generated by Django 5.0 on 2025-04-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personnels",
            "0004_alter_user_address_alter_user_nom_alter_user_prenoms_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Administrateur"), ("CASHIER", "Caissier")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
