# Generated by Django 5.0 on 2025-04-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnels", "0005_remove_user_address_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name=""),
        ),
    ]
