# Generated by Django 5.0 on 2025-05-04 09:39

import personnels.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnels", "0006_user_address"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", personnels.models.CustomUserManager()),
            ],
        ),
    ]
