# Generated by Django 5.0 on 2024-10-11 11:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('adresse', models.TextField()),
                ('ancienne_dette', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('dette', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='fournieur_logo.png', upload_to='logo')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('adresse', models.TextField()),
                ('dette', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('ancienne_dette', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
